version: "3"

env:
  DOMAIN: "booky.kids"
  APP_NAME: "sipoor-im"
  APP_REPO: "sipoor-im/web"
  TXT_NAME: "Booky"

tasks:
  publish:
    cmds:
      # - poetry version patch
      # - poetry publish --build
      # - git tag $(poetry version -s)
      - git commit -am "$(poetry version)"
      - git push
